name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CC: gcc-11
  CXX: g++-11

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler:
          - { compiler: gcc, CC: gcc-11, CXX: g++-11 }
          - { compiler: clang, CC: clang, CXX: clang++ }
        configuration: [Debug, Release, RelWithDebInfo]
        sanitize: [none, undefined]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install gcc 11
        run:   |
          sudo apt update
          sudo apt install gcc-11 g++-11
        shell: bash
        if: ${{matrix.compiler.compiler == 'gcc'}}

      - name: Install valgrind
        run:   |
          sudo apt update
          sudo apt install valgrind
        shell: bash
        if: ${{matrix.sanitize == 'none' && matrix.os == 'linux-latest'}}

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            ./llvm
          key: llvm-12.0.1
        if: ${{matrix.compiler.compiler == 'clang'}}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0.1"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        if: ${{matrix.compiler.compiler == 'clang'}}




    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -DSANITIZE=${{matrix.sanitize}}
      env:
        CC: ${{matrix.compiler.CC}}
        CXX: ${{matrix.compiler.CXX}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}} --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.configuration}}

    - name: Test with valgrind
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: valgrind --trace-children=yes ctest -C ${{matrix.configuration}} -j 3
      if: ${{matrix.sanitize == 'none' && matrix.os == 'linux-latest'}}
      
